# Generated by Django 4.2.9 on 2024-07-23 04:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(max_length=500)),
                ('updated_on', models.DateField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=300)),
                ('next_step', models.CharField(blank=True, max_length=200)),
                ('data_json', jsonfield.fields.JSONField(blank=True)),
                ('path_json', jsonfield.fields.JSONField(blank=True, default=list)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='custom_components.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CreateProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(blank=True, max_length=200)),
                ('process_description', models.CharField(blank=True, max_length=200, null=True)),
                ('initiator_group', models.IntegerField(blank=True, null=True)),
                ('prefix', models.CharField(blank=True, max_length=255)),
                ('first_step', models.CharField(blank=True, max_length=255)),
                ('participants', jsonfield.fields.JSONField(blank=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_process', to='custom_components.organization')),
                ('usergroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_create_process', to='custom_components.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='FormDataInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_uid', models.CharField(blank=True, max_length=50)),
                ('form_description', models.CharField(blank=True, max_length=50)),
                ('form_name', models.CharField(blank=True, max_length=200)),
                ('form_json_schema', jsonfield.fields.JSONField(blank=True)),
                ('form_status', models.BooleanField(default=False)),
                ('form_created_by', models.CharField(blank=True, default='admin', max_length=200)),
                ('form_created_on', models.DateField(default=datetime.date.today)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data_info', to='custom_components.organization')),
                ('processId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.createprocess')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='custom_components.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Sla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slaId', models.CharField(blank=True, max_length=200)),
                ('sla_json_schema', jsonfield.fields.JSONField(blank=True)),
                ('caseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.case')),
                ('processId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.createprocess')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleId', models.CharField(blank=True, max_length=200)),
                ('rule_type', models.CharField(blank=True, max_length=200)),
                ('rule_json_schema', jsonfield.fields.JSONField(blank=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='custom_components.organization')),
                ('processId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.createprocess')),
            ],
        ),
        migrations.CreateModel(
            name='FormPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_generator.formdatainfo')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_permission', to='custom_components.usergroup')),
            ],
            options={
                'unique_together': {('user_group', 'form')},
            },
        ),
        migrations.AddField(
            model_name='formdatainfo',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='usergroup_form_data_info', through='form_generator.FormPermission', to='custom_components.usergroup'),
        ),
        migrations.CreateModel(
            name='FilledFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formId', models.CharField(blank=True, max_length=200)),
                ('data_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=500, null=True)),
                ('caseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.case')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filled_data', to='custom_components.organization')),
                ('processId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.createprocess')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_generator.userdata')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='processId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_generator.createprocess'),
        ),
    ]
