# Generated by Django 4.2.9 on 2024-07-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0007_dms_flow_id'),
        ('form_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='username',
            new_name='mail_id',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='usergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_user_data', to='custom_components.usergroup'),
        ),
    ]
