# Generated by Django 4.2.9 on 2024-07-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0004_alter_userdata_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
