# Generated by Django 4.2.9 on 2024-07-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0005_userdata_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='role',
        ),
    ]
