# Generated by Django 4.2.9 on 2024-07-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0006_remove_userdata_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='mail_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
