# Generated by Django 4.2.9 on 2024-07-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0007_alter_userdata_mail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
