# Generated by Django 4.2.9 on 2024-08-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0009_userdata_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='user_id',
            new_name='user',
        ),
    ]
