# Generated by Django 4.2.9 on 2024-08-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0010_rename_user_id_userdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createprocess',
            old_name='usergroup',
            new_name='user_group',
        ),
    ]
