# Generated by Django 4.2.9 on 2024-08-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0013_alter_dms_data_download_link'),
        ('form_generator', '0011_rename_usergroup_createprocess_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createprocess',
            name='user_group',
        ),
        migrations.AddField(
            model_name='createprocess',
            name='user_group',
            field=models.ManyToManyField(blank=True, null=True, related_name='usergroup_create_process', to='custom_components.usergroup'),
        ),
    ]
