# Generated by Django 4.2.9 on 2024-08-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0013_alter_dms_data_download_link'),
        ('form_generator', '0012_remove_createprocess_user_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createprocess',
            name='user_group',
            field=models.ManyToManyField(blank=True, related_name='usergroup_create_process', to='custom_components.usergroup'),
        ),
    ]
