# Generated by Django 4.2.9 on 2024-08-17 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0013_alter_dms_data_download_link'),
        ('form_generator', '0013_alter_createprocess_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='filledformdata',
            name='user_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_filled_form_data', to='custom_components.usergroup'),
        ),
    ]
