# Generated by Django 4.2.9 on 2024-08-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0014_filledformdata_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='filledformdata',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
