# Generated by Django 4.2.9 on 2024-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0015_filledformdata_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='filledformdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
