# Generated by Django 4.2.9 on 2024-08-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0016_alter_case_created_on_alter_case_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
