# Generated by Django 4.2.9 on 2024-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0013_alter_dms_data_download_link'),
        ('form_generator', '0017_alter_case_created_on_alter_case_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filledformdata',
            name='user_groups',
        ),
        migrations.AddField(
            model_name='filledformdata',
            name='user_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='usergroup_filled_form_data', to='custom_components.usergroup'),
        ),
    ]
