# Generated by Django 4.2.9 on 2024-08-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0014_alter_dms_data_updated_at'),
        ('form_generator', '0018_remove_filledformdata_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filledformdata',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='usergroup_filled_form_data', to='custom_components.usergroup'),
        ),
    ]
