# Generated by Django 4.2.9 on 2024-07-23 04:43

import custom_components.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_uid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('bot_name', models.CharField(choices=[('google_drive', 'google_drive'), ('email', 'email'), ('screen_scraping', 'screen_scraping'), ('file_extractor', 'file_extractor')], default='google_drive', max_length=100)),
                ('bot_description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_schema', jsonfield.fields.JSONField(blank=True)),
                ('temp_data', models.FileField(blank=True, null=True, upload_to=custom_components.models.user_directory_path)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_schema_json', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dashboard_types', models.CharField(blank=True, max_length=100, null=True)),
                ('dashboard_config', jsonfield.fields.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dms_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('drive_types', models.CharField(choices=[('Google Drive', 'Google Drive'), ('S3 Bucket', 'S3 Bucket'), ('One Drive', 'One Drive')], default='Google Drive', max_length=100)),
                ('config_details_schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dms_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('folder_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Integration_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('integration_type', models.CharField(choices=[('api', 'api')], default='api', max_length=100)),
                ('integration_name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('integration_schema', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('ocr_type', models.CharField(choices=[('Aadhar Card Extraction', 'Aadhar Card Extraction'), ('Pan Card Extraction', 'Pan Card Extraction'), ('PDF to TEXT Extraction', 'Pan Card Extraction')], default='Aadhar Card Extraction', max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocr_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('data_schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('org_code', models.CharField(max_length=5, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('org_description', models.TextField(blank=True, null=True)),
                ('large_logo_url', models.URLField(blank=True, null=True)),
                ('small_logo_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=10, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=10, null=True)),
                ('accent1_color', models.CharField(blank=True, max_length=10, null=True)),
                ('accent2_color', models.CharField(blank=True, max_length=10, null=True)),
                ('accent3_color', models.CharField(blank=True, max_length=10, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_components.bot')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_description', models.TextField()),
                ('status', models.BooleanField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='custom_components.organization')),
            ],
        ),
    ]
