# Generated by Django 4.2.9 on 2024-07-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_components', '0001_initial'),
        ('form_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_process', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='ocr_details',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_ocr_details', to='form_generator.case'),
        ),
        migrations.AddField(
            model_name='ocr_details',
            name='flow_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='process_ocr_details', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='ocr_details',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_details', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='ocr',
            name='flow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_ocr', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='ocr',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='integrationdetails',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_integration_details', to='form_generator.case'),
        ),
        migrations.AddField(
            model_name='integrationdetails',
            name='flow_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='integration_details', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='integrationdetails',
            name='integration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_components.integration'),
        ),
        migrations.AddField(
            model_name='integrationdetails',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_integration_details', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='integration',
            name='flow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_integration_schema', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='integration',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_schema', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_dms_data', to='form_generator.case'),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='dms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dms_dms_data', to='custom_components.dms'),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='flow_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dms_data', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_dms_data', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='usergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_dms_data', to='custom_components.usergroup'),
        ),
        migrations.AddField(
            model_name='dms',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dms', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='usergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_dashboard', to='custom_components.usergroup'),
        ),
        migrations.AddField(
            model_name='botschema',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_components.bot'),
        ),
        migrations.AddField(
            model_name='botschema',
            name='flow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_bot_schema', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='botschema',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_schema', to='custom_components.organization'),
        ),
        migrations.AddField(
            model_name='botdata',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_components.bot'),
        ),
        migrations.AddField(
            model_name='botdata',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_bot_data', to='form_generator.case'),
        ),
        migrations.AddField(
            model_name='botdata',
            name='flow_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_data', to='form_generator.createprocess'),
        ),
        migrations.AddField(
            model_name='botdata',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_bot_data', to='custom_components.organization'),
        ),
    ]
