# Generated by Django 4.2.9 on 2024-07-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0001_initial'),
        ('custom_components', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dms',
            name='flow_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flow_dms', to='form_generator.createprocess'),
        ),
    ]
