# Generated by Django 4.2.9 on 2024-07-23 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0001_initial'),
        ('custom_components', '0003_dms_flow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dms',
            name='flow_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_dms', to='form_generator.createprocess'),
        ),
    ]
