# Generated by Django 4.2.9 on 2024-07-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0005_alter_dms_flow_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dms',
            name='flow_id',
        ),
    ]
