# Generated by Django 4.2.9 on 2024-07-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0007_dms_flow_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='process',
        ),
        migrations.AlterField(
            model_name='dms',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_components.organization'),
        ),
    ]
