# Generated by Django 4.2.9 on 2024-07-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0008_remove_organization_process_alter_dms_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dms',
            old_name='drive_types',
            new_name='dms_data',
        ),
    ]
