# Generated by Django 4.2.9 on 2024-07-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0009_rename_drive_types_dms_dms_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dms',
            old_name='dms_data',
            new_name='drive_types',
        ),
    ]
