# Generated by Django 4.2.9 on 2024-07-31 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0010_rename_dms_data_dms_drive_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='status',
        ),
    ]
