# Generated by Django 4.2.9 on 2024-08-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0011_remove_dashboard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dms_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='download_link',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='dms_data',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='botschema',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_components.bot'),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='ocr_type',
            field=models.CharField(choices=[('Aadhar Card Extraction', 'Aadhar Card Extraction'), ('Pan Card Extraction', 'Pan Card Extraction'), ('PDF Extraction', 'PDF Extraction'), ('QR Extraction', 'QR Extraction')], default='Aadhar Card Extraction', max_length=100),
        ),
    ]
