# Generated by Django 4.2.9 on 2024-08-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0012_dms_data_created_at_dms_data_download_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dms_data',
            name='download_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
