# Generated by Django 4.2.9 on 2024-08-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_components', '0013_alter_dms_data_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dms_data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
